version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    groups:
      actions-dependencies:
        applies-to: version-updates
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 5

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    groups:
      golang:
        applies-to: security-updates
        patterns:
          - "golang.org*"
      support-dependencies:
        applies-to: version-updates
        patterns:
          - "*"
